version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine3.20
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./static:/usr/share/nginx/static:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api # Garante que o serviço 'api' inicie antes do nginx
    networks:
      - app-network

  api:
    build:
      context: ./api
    container_name: api-server
    ports:
      - "9001:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
