version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine3.20
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
