version: "3.9" # Versão do Docker Compose
services:
  nginx:
    image: nginx:stable-alpine3.20
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./static:/usr/share/nginx/static:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
